<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Editorial;

class EditorialsSeederSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $editorials = [
            'A buen paso',
            'Abada Editores',
            'Absalon',
            'Acantilado',
            'Acanto',
            'ACCI',
            'ACCI con FEHM',
            'Acribia',
            'Actas',
            'Adams',
            'AdN',
            'Adriana Hidalgo Editora',
            'Aebius',
            'Aena',
            'Aenor',
            'Aguilar',
            'Aguilar Ocio',
            'Akal',
            'Akiara',
            'Alamut',
            'Alba',
            'Alberto Santos Editor',
            'Alcalá',
            'Alcañiz Fresnos Editores',
            'Aleta',
            'Alethé',
            'Alevosía',
            'Alfabia',
            'Alfaguara',
            'Alfaguara Infantil y Juvenil',
            'Alfar',
            'Algaida Editores',
            'Algar',
            'Alhena Media',
            'Alianza',
            'Alienta',
            'Aljibe',
            'Alma',
            'Almajara',
            'Almuzara',
            'Alrevés',
            'Altea',
            'Áltera',
            'Alpha Decay',
            'Alpina',
            'Altaïr',
            'Amanecer',
            'Amaníaco',
            'Amarrortu editores',
            'Amarú Ediciones',
            'Amazing Books',
            'Armaenia',
            'Anagrama',
            'Anaya Educación',
            'Anaya ELE',
            'Anaya Infantil y Juvenil',
            'Anaya Multimedia',
            'Anaya Touring',
            'Antígona',
            'Antoni Bosch Editor',
            'Apa Apa Cómics',
            'Apache Libros',
            'Apila Ediciones',
            'Arán',
            'Araña Editorial',
            'Arco/Libros',
            'Ardicia',
            'Arena Libros',
            'Ariane',
            'Ariel',
            'Arguval',
            'Arkano Books',
            'Armaenia',
            'Arpa',
            'Arquia',
            'Artistas Martínez',
            'Astiberri',
            'Athenaica',
            'Atlanta',
            'Atrapada',
            'Austral',
            'Ático de los libros',
            'Atlantis',
            'Automática',
            'Avenauta',
            'B de Block',
            'B de Bolsillo',
            'B de Books',
            'Babylon',
            'Bagua',
            'Bainet',
            'Bambú',
            'Bang',
            'Barbara Fiore Editora',
            'Bartleby Editores',
            'Base',
            'Beascoa',
            'Bellaterra Música',
            'Bestia Negra',
            'Beta, Ediciones',
            'Beta Editorial',
            'BiblioGemma',
            'Biblioteca Deliberar',
            'Biblioteca Nueva',
            'Blackie Books',
            'BlackList',
            'Blume',
            'Boileau',
            'Boira',
            'Booket',
            'Bookolia',
            'Books4pocket',
            'Boreal',
            'Bóveda',
            'Bridge',
            'Brief',
            'Bruguera',
            'Bruño Educación',
            'Bruño Publicaciones Generales',
            'Bululú',
            'Caballo de Troya',
            'Cabaret Voltaire',
            'Caelus',
            'Café con leche',
            'Caïrel',
            'Calambur',
            'Cálamo',
            'Campgràfic',
            'Candaya',
            'Carambuco Ediciones',
            'Carena',
            'Casals',
            'Casiopea',
            'Catarata',
            'Cátedra',
            'Catedral',
            'Caudal',
            'Cazador de ratas',
            'CCS',
            'CEEH',
            'CEF',
            'CEP',
            'CERASA',
            'Cerbero',
            'Cetea Ediciones',
            'Cinco tintas',
            'Cinter',
            'Círculo',
            'Cisma',
            'Cisne',
            'Ciudad de libros',
            'Ciudad nueva',
            'Clan',
            'Clave Intelectual',
            'Click',
            'Clie',
            'Cliper',
            'CLP',
            'Coco Books',
            'Colex',
            'Collins',
            'Combel',
            'Complutense, Ediciones',
            'Comunicación Social',
            'Conecta',
            'Confluencias',
            'Consonni',
            'Contra',
            'Corimbo',
            'Corín Tellado, Ediciones',
            'Córner',
            'Creación',
            'Cristiandad, Ediciones',
            'Crítica',
            'Crononauta',
            'CSIC',
            'Cuadernos del laberinto',
            'Cuadernos del vigía',
            'Cuanto te quiero',
            'Cuento de Luz',
            'Cydonia',
            'Daly',
            'Dardo',
            'Dastin',
            'Dauro',
            'De Librum Tremens',
            'Debate',
            'Debolsillo',
            'Defausta',
            'Del Nuevo Extremo',
            'Delirio',
            'Desclée de Brouwer',
            'Demipage',
            'Descrito',
            'Desperta Ferro',
            'Destino',
            'Destino Infantil & Juvenil',
            'Época',
            'Desnivel',
            'Deusto',
            'Deusto Publicaciones',
            'Devir',
            'Dharma',
            'Diábolo Ediciones',
            'Diada',
            'Diálogo',
            'Dibbuks',
            'Diego Pun',
            'Diëresis',
            'Difácil',
            'Difusión',
            'Difusora de letras',
            'Dilatando mentes',
            'Dioptrías',
            'Diquesí',
            'Dirty Works',
            'DK',
            'Doce Calles',
            'Doblerre',
            'Dojo Ediciones',
            'Dokosou',
            'Dolmen Editorial',
            'Dorna',
            'Drac',
            'Drakul',
            'Duermevela Ediciones',
            'Duomo Ediciones',
            'Dykinson',
            'Dylar',

            'Ecobook',
            'ECOE Ediciones',
            'ED Libros',
            'EDA libros',
            'Edaf',
            'Edebé',
            'Edelsa',
            'Edelvives',
            'Edex',
            'Edhasa',
            'Ediasa',
            'Edibesa',
            'Ediciones 19',
            'Ediciones B',
            'Ediciones de la Torre',
            'Ediciones del viento',
            'Ediciones & Escultura Histórica',
            'Edigol',
            'Edigrama',
            'Edimat',
            'Edinumen',
            'Editex',
            'Editum',
            'EDL',
            'EFL',
            'Eikon',
            'Eirene',
            'Ekaré',
            'El Aleph Editores',
            'El Croquis',
            'El Nadir',
            'El Rompecabezas',
            'El senderista',
            'El transbordador',
            'Electa',
            'Eleftheria',
            'Emecé Editores',
            'Empresa activa',
            'enClave-ELE',
            'Encuentro',
            'Eneida',
            'Enfermería 21',
            'Entorno Gráfico',
            'Entramat',
            'Entre líneas Editores',
            'Éride',
            'Errata Naturae',
            'Es Pop',
            'Escarlata Ediciones',
            'Esdrújula',
            'Esencia',
            'ESIC',
            'Espacio Cultura Editores',
            'Espasa',
            'Espasa Infantil',
            'Espiritualidad',
            'Espuela de Plata',
            'Esqueleto negro',
            'EUNSA',
            'Experiencia',
            'Faktoría K de Libros',
            'FAL',
            'Fantascy',
            'FCEDE',
            'Fineo',
            'Flamboyant',
            'Flash',
            'Flow Press',
            'Fórcola',
            'Formación Alcalá',
            'Fortuna, Ediciones',
            'Franciscanas Arantzazu, Ediciones',
            'Freya, Ediciones',
            'Fulgencio Pimentel',
            'Funambulista',
            'Fundación Anastasio de Gracia',
            'Fundación Bamberg',
            'Fundación José Antonio de Castro',
            'Fundación José Manuel Lara',
            'Fundación Málaga',
            'Fundación Pablo Iglesias',
            'Fundación Santa María La Real',
            'Fundación SGAE',
            'Fundamentos',
            'GAESA, Ediciones',
            'Gaia',
            'Gadir',
            'Gakoa',
            'Galaxia Gutenberg',
            'GaliNova',
            'Gallo Nero',
            'Garceta',
            'Gatopardo',
            'Gedisa',
            'GeoPlaneta',
            'Gestión 2000',
            'GEU Editorial',
            'Gigamesh',
            'Glyphos',
            'Good Books',
            'GPS, Ediciones',
            'Gradiva',
            'Grafito',
            'Gran Travesía',
            'Graó',
            'Gredos',
            'Grijalbo',
            'Grijalbo Ilustrados',
            'Grupo Cero',
            'Guía Burros',
            'Guillermo Escolar || Editor',
            'Gulaab',
            'Gustavo Gili',
            'Hachette Héroes',
            'Harlequín',
            'Harper Collins',
            'Harper Kids',
            'Hati',
            'Hela',
            'Hélice',
            'Hércules de Ediciones',
            'Herder',
            'Hermenaute',
            'Hermida Editores',
            'Hidra',
            'Hiperión',
            'Hispano Europea',
            'Hoja de lata',
            'HQN',
            'HQÑ',
            'Huerga & Fierro',
            'Huevo Cósmico',
            'Huso',
            'Iberia',
            'Iberoamericana / Vervuert',
            'Iberlibro',
            'Iberoamericana Vervuert',
            'IC Editorial',
            'Icaria',
            'ICB Book',
            'ICCE',
            'Idampa',
            'Ideas Propias',
            'Ifeelbook',
            'Ilusbooks',
            'Imágica',
            'Impedimenta',
            'Inde',
            'Indicios',
            'ING Edicions',
            'Insólita Editorial',
            'Integral',
            'Instituto de Estudios Económicos',
            'Instituto de Orientación Psicológica',
            'Interfolio',
            'Irreverentes',
            'Istarduk Ediciones',
            'Iustel',
            'Jabalí',
            'Jaguar, Ediciones',
            'JC, Ediciones',
            'Jus',
            'Juventud',
            'Kailas',
            'Kairós',
            'Kakao Books',
            'Kalandraka',
            'Karma 7',
            'Katz',
            'Kepler',
            'Kitsune Books',
            'Kiwi',
            'KNS Ediciones',
            'Kókinos',
            'Kolima',
            'Kraken',
            'La Bella Varsovia',
            'La biblioteca de Carfax',
            'La Calle',
            'La Cúpula',
            'La Dragona',
            'La esfera de los libros',
            'La Fábrica',
            'La Felguera',
            'La Fertilidad de la Tierra',
            'La Fuga',
            'La Galera',
            'La Guarida',
            'La huerta grande',
            'La librería',
            'La línea del horizonte',
            'La máquina que hace PING!',
            'La Muralla',
            'La navaja suiza',
            'La Oficina de Arte y Ediciones',
            'La oveja roja',
            'La palma',
            'La poesía mancha',
            'La señora Dalloway',
            'La Tribu',
            'La umbría y la solana',
            'La uña rota',
            'Laberinto',
            'Labnar, Ediciones',
            'Laertes',
            'Larousse',
            'Lata de sal',
            'Lectura Plus',
            'Lengua de trapo',
            'LES Editorial',
            'Liber Factory',
            'Libertarias',
            'Libre Albedrío',
            'Librooks',
            'Libros Cúpula',
            'Libros de Cabecera',
            'Libros del Asteroide',
            'Libros del K.O.',
            'Libros de la ballena',
            'Libros de seda',
            'Libros Disney',
            'Libros Libres',
            'Libsa',
            'LID Editorial',
            'Lince',
            'Linteo',
            'Litera',
            'Literatura Random House',
            'Lo que leo',
            'Lóguez Ediciones',
            'Loyola',
            'Los cuatro azules',
            'Lu',
            'Luciérnaga, Ediciones',
            'Luis Cárcamo',
            'Lumen',
            'Lumen Infantil',
            'Lunwerg Editores',
            'Lxl Editorial',
            'M. Moleiro Editor',
            'Ma non troppo',
            'Macmillan',
            'Maeva',
            'Malpaso',
            'Mamut Cómics',
            'Marban Libros',
            'Marcial Pons, Ediciones Jurídicas y Sociales',
            'Marcial Pons, Ediciones de Historia',
            'Marcombo',
            'Mármara',
            'Martínez Roca',
            'Max Estrella',
            'MaxiTusquets',
            'Maxtor',
            'Mayo, Ediciones',
            'McGraw Hill',
            'MCSports',
            'Medialive Content',
            'Médica Panamericana',
            'Medici',
            'Mediterrània',
            'Meiga Ediciones',
            'Melusina',
            'Ménades',
            'Meracovia',
            'Meteora',
            'Mestas Ediciones',
            'Michelín (Mapas y Guías)',
            'Mil y un Cuentos',
            'Milenio',
            'Mily Way',
            'Millenium Liber',
            'Milrazones',
            'Minobitia',
            'Minotauro',
            'Minúscula',
            'Mira Editores',
            'Miraguano',
            'Mirach',
            'Modernito Books',
            'Molino',
            'Monsquito Books Barcelona',
            'Montecarmelo',
            'Montena',
            'Morata',
            'MTM Editor',
            'Musivisual',
            'Nadal Aderca',
            'Narcea',
            'Nau Llibres',
            'Naufragio de letras',
            'Nausícaä',
            'Neo Person',
            'Nerea',
            'Neverland Ediciones',
            'Nevsky',
            'Nickelodeon',
            'Nivola',
            'Nocturna Ediciones',
            'Noguer',
            'Nørdica Libros',
            'Norma-Capitel, Ediciones',
            'Norma Editorial',
            'Notorious Ediciones',
            'Nova',
            'Now Books',
            'Nowevolution',
            'Nowtilus',
            'Nube de Tinta',
            'NubeOcho',
            'Obelisco',
            'Oberon',
            'Octaedro Editorial',
            'Olé Libros',
            'Olmak Trade',
            'Omega',
            'Oniro',
            'Oniro Infantil',
            'Onyx',
            'Orbis Medievalis',
            'Ortells',
            'Oxford University Press',
            'Oz',
            'Páginas de Espuma',
            'Paidós',
            'Paidotribo',
            'Palabra',
            'Pálido Fuego',
            'Pamiés',
            'Para Dummies',
            'Paraninfo',
            'Parramon',
            'Pasado y Presente',
            'Pasos Perdidos',
            'Pastel de Luna',
            'Patrimonio',
            'Paulinas',
            'Pearson',
            'Penguin Clásicos',
            'Península',
            'Pepitas',
            'Periférica',
            'Perpetuo Socorro',
            'Pez de Plata',
            'Phoebe',
            'Piedra Papel',
            'Piles',
            'Piolet',
            'Pirámide',
            'Pispás',
            'Plan B',
            'Planeta',
            'Planeta Cómic',
            'Planeta DeAgostini',
            'Planeta Gastro',
            'Planeta Gifts',
            'Planeta Junior',
            'PlanetaLector',
            'Plata',
            'Plataforma',
            'Plataforma Neo',
            'Plaza & Janés',
            'Plaza & Valdés',
            'Pléyades',
            'Pliegos',
            'Plot Ediciones',
            'Plutón Ediciones',
            'Photo Club',
            'Polifemo',
            'Popular',
            'PPC',
            'Premium',
            'Pre-Textos',
            'Profit',
            'Progensa',
            'Proteus',
            'Proyecto Argán',
            'Psicoterapia relacional',
            'Psimática Editorial',
            'Publicaciones Claretianas',
            'Puck',
            'Punto de Lectura',
            'Punto de Vista',
            'Quaterni',
            'Raíces',
            'Ra-Ma',
            'Random Cómics',
            ':Rata_',
            'Rayo verde',
            'RBA',
            'RBA Coleccionables',
            'RBA Gastronomía y Cocina',
            'RBA No Ficción',
            'RBA Práctica',
            'RC Libros',
            'Real Academia Española',
            'Real Musical',
            'Reino de Cordelia',
            'Renacimiento',
            'Renden Institut Gestalt',
            'Reservoir Books',
            'Reus',
            'Reverté',
            'Rialp',
            'Robin Book',
            'Roca Bolsillo',
            'Roca Editorial',
            'Roca Juvenil',
            'RM',
            'Romeo Ediciones',
            'Rudolf Steiner',
            'Rueda',
            'Saco de huesos',
            'Safeliz',
            'Sajalín Editores',
            'Salamandra',
            'Saldaña',
            'Salsa Books',
            'Salvat',
            'Salvatella!',
            'San Esteban',
            'San Pablo',
            'Sankara Books',
            'Santa & Cole',
            'Santillana',
            'Sanz y Torres',
            'Sapristi',
            'Satori Ediciones',
            'Saralejandria',
            'Scyla eBooks',
            'Secretariado Trinitario',
            'Seeler',
            'Seix Barral',
            'Selecta',
            'Sensi Romero',
            'Sepin',
            'Septem Ediciones',
            'Serbal, Ediciones del',
            'Serie Negra',
            'Sexto Piso',
            'Siete islas',
            'Siete Leguas',
            'Signo Editores',
            'Sígueme, Ediciones',
            'Sílex',
            'Sinsentido',
            'Síntesis',
            'Sirio',
            'Siruela',
            'SM',
            'SM Infantil y Juvenil',
            'Suma de letras',
            'Sushi Books',
            'Swing',
            'Tabarca Llibres',
            'TakaTuka',
            'Talentura',
            'Tandaia',
            'Tàndem Edicions',
            'Taurus',
            'Tea',
            'Tébar Flores',
            'Tecnos',
            'Teide',
            'Telstar (Distrimapas)',
            'Temas de Hoy',
            'Terapias Verdes',
            'Terciopelo',
            'Testimonio',
            'The Black House',
            'Thule Ediciones',
            'Tibidabo',
            'Tilde',
            'Timun Mas Infantil',
            'Timun Mas Narrativa',
            'Tirant Editorial',
            'Titania',
            'Títiris',
            'Todolibro',
            'Top Novel',
            'Torremozas',
            'Trama Editorial',
            'Tránsito',
            'Trea',
            'Tres Hermanas',
            'Tres Tigres Tristes',
            'Tria Ediciones',
            'Trifaldi',
            'Tritó',
            'Tropo',
            'Trotalibros',
            'Trotamundos',
            'Trotta',
            'Turner',
            'Tushita',
            'Tusquets Editores',
            'Tutor',
            'Umbriel',
            'Underwood',
            'UNED',
            'Unión',
            'Universidad Salamanca, Ediciones',
            'UPV',
            'Útero Libros',
            'Urano',
            'Urgoitieditores',
            'Urmo',
            'Uve Books',
            'Valdemar',
            'Valhalla',
            'Valparaíso',
            'Vanir',
            'Vaso Roto',
            'Vegueta',
            'Verbo Divino',
            'Verbum',
            'Vergara',
            'Versátil',
            'Verticales de Bolsillo',
            'Vicens Vives',
            'Videocinco',
            'Vision Ebooks',
            'Vision Libros',
            'Visor Libros',
            'Vox',
            'VV Kids',
            'Wave Books',
            'Wonder Ponder',
            'WunderKammer',
            'Xordica Editorial',
            'Xorki',
            'Xplora',
            'Yermo Ediciones',
            'Ya lo dijo Casimiro Parker',
            'Yoyo',
            'Zafiro eBooks',
            'Zahorí de ideas',
            'Zenith',
            'Zorro rojo',
            'Zumaque',
        ];

        foreach ($editorials as $editorial) {
            Editorial::create(['name' => $editorial]);
        }
    }
}
